### ISSUE TITLE
Example tables highlighting fails if last pipe is missing

### ISSUE THREAD

**Issue by PunchyRascal** [euclidity/vscode-cucumber#11] opened 2016-10-12 13:04 UTC
If I have data table in cucumber file:

``` cucumber
        | total | currency | date
        | 100   | USD      | 2 days ago
```

then all the rest of the file is considered a continuation of the "2 days ago" line (and so highlighting is messed). If I add pipe symbol ("|") to the end of that line, it works fine. It would be nice if the highlighter could handle this situation.

**Comment by dialex** [comment] 2018-02-28 09:05
That's the expected behaviour. Tables should end with a `|` symbol, your example is of a broken table. Therefore the highlighter will think the table continues, until it finds the next `|`. 

We won't fix/change anything, because our current implementation is according to the Gherkin syntax.

**Closed as completed by dialex** 2018-02-28 09:05 UTC
Labels: wontfix
